# Generated by Django 5.0.2 on 2024-03-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="idade",
            field=models.IntegerField(default=True),
        ),
    ]
