# Generated by Django 5.0.2 on 2024-03-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_categoria_idade"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="nome",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
