# Generated by Django 5.0.2 on 2024-03-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_categoria_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="autor",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="categoria",
            name="idade",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nome",
            field=models.CharField(default="Sem nome", max_length=50),
        ),
    ]
